services:
  toolbox:
    build: .
    volumes:
      - "C:/Users/p70092896/OneDrive - Maastricht University/Desktop/AIDAVA/test/precision-medicine-toolbox/data2:/app/data"
    environment:
      DATA_PATH: /app/data
      DATA_TYPE: dcm
      MULTI_RTS_PER_PAT: "False"
      TWOD_IMAGE: "True"
      PRE_PROCESSED_PATH: /app/data/preprocessed
      OUT_DICOM_PATH: /app/data/converted_dicoms
    ports:
      - "8000:8000"
